// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiALMTextil;

namespace WebApiALMTextil.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210906193342_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiALMTextil.Entities.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Usuarioid")
                        .HasColumnType("int");

                    b.Property<string>("apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("nombre_Usuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombres")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Usuarioid");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("WebApiALMTextil.Entities.ContactoUsuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codigo_postal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("ContactoUsuarios");
                });

            modelBuilder.Entity("WebApiALMTextil.Entities.DetallePedido", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Prendaid")
                        .HasColumnType("int");

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_Pedido")
                        .HasColumnType("int");

                    b.Property<int>("id_Prenda")
                        .HasColumnType("int");

                    b.Property<DateTime>("modified_at")
                        .HasColumnType("datetime2");

                    b.Property<float>("precio")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("Prendaid");

                    b.ToTable("DetallePedidos");
                });

            modelBuilder.Entity("WebApiALMTextil.Entities.Empresa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Localid")
                        .HasColumnType("int");

                    b.Property<int?>("Usuarioid")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_Local")
                        .HasColumnType("int");

                    b.Property<int>("id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ruc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Localid");

                    b.HasIndex("Usuarioid");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("WebApiALMTextil.Entities.Local", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nombre_Sede")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Locales");
                });

            modelBuilder.Entity("WebApiALMTextil.Entities.Medidas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Clienteid")
                        .HasColumnType("int");

                    b.Property<string>("datos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_Cliente")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Clienteid");

                    b.ToTable("Medidas");
                });

            modelBuilder.Entity("WebApiALMTextil.Entities.Pedido", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Clienteid")
                        .HasColumnType("int");

                    b.Property<int?>("Empresaid")
                        .HasColumnType("int");

                    b.Property<int?>("Localid")
                        .HasColumnType("int");

                    b.Property<int?>("Medidasid")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_Entrega")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_Cliente")
                        .HasColumnType("int");

                    b.Property<int>("id_Empresa")
                        .HasColumnType("int");

                    b.Property<int>("id_Local")
                        .HasColumnType("int");

                    b.Property<int>("id_Medidas")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Clienteid");

                    b.HasIndex("Empresaid");

                    b.HasIndex("Localid");

                    b.HasIndex("Medidasid");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("WebApiALMTextil.Entities.Prenda", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Telaid")
                        .HasColumnType("int");

                    b.Property<int?>("TipoPrendaid")
                        .HasColumnType("int");

                    b.Property<int>("id_Tela")
                        .HasColumnType("int");

                    b.Property<int>("id_tipoPrenda")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Telaid");

                    b.HasIndex("TipoPrendaid");

                    b.ToTable("Prendas");
                });

            modelBuilder.Entity("WebApiALMTextil.Entities.Tela", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("material")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Telas");
                });

            modelBuilder.Entity("WebApiALMTextil.Entities.TipoDoc", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descrip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TipoDocs");
                });

            modelBuilder.Entity("WebApiALMTextil.Entities.TipoPrenda", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("desc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TipoPrendas");
                });

            modelBuilder.Entity("WebApiALMTextil.Entities.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("TipoDocid")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idtipo_Doc")
                        .HasColumnType("int");

                    b.Property<string>("nombre_Usuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("TipoDocid");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("WebApiALMTextil.Entities.Cliente", b =>
                {
                    b.HasOne("WebApiALMTextil.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Usuarioid");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebApiALMTextil.Entities.DetallePedido", b =>
                {
                    b.HasOne("WebApiALMTextil.Entities.Prenda", "Prenda")
                        .WithMany()
                        .HasForeignKey("Prendaid");

                    b.Navigation("Prenda");
                });

            modelBuilder.Entity("WebApiALMTextil.Entities.Empresa", b =>
                {
                    b.HasOne("WebApiALMTextil.Entities.Local", "Local")
                        .WithMany()
                        .HasForeignKey("Localid");

                    b.HasOne("WebApiALMTextil.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Usuarioid");

                    b.Navigation("Local");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebApiALMTextil.Entities.Medidas", b =>
                {
                    b.HasOne("WebApiALMTextil.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("Clienteid");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("WebApiALMTextil.Entities.Pedido", b =>
                {
                    b.HasOne("WebApiALMTextil.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("Clienteid");

                    b.HasOne("WebApiALMTextil.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("Empresaid");

                    b.HasOne("WebApiALMTextil.Entities.Local", "Local")
                        .WithMany()
                        .HasForeignKey("Localid");

                    b.HasOne("WebApiALMTextil.Entities.Medidas", "Medidas")
                        .WithMany()
                        .HasForeignKey("Medidasid");

                    b.Navigation("Cliente");

                    b.Navigation("Empresa");

                    b.Navigation("Local");

                    b.Navigation("Medidas");
                });

            modelBuilder.Entity("WebApiALMTextil.Entities.Prenda", b =>
                {
                    b.HasOne("WebApiALMTextil.Entities.Tela", "Tela")
                        .WithMany()
                        .HasForeignKey("Telaid");

                    b.HasOne("WebApiALMTextil.Entities.TipoPrenda", "TipoPrenda")
                        .WithMany()
                        .HasForeignKey("TipoPrendaid");

                    b.Navigation("Tela");

                    b.Navigation("TipoPrenda");
                });

            modelBuilder.Entity("WebApiALMTextil.Entities.Usuario", b =>
                {
                    b.HasOne("WebApiALMTextil.Entities.TipoDoc", "TipoDoc")
                        .WithMany()
                        .HasForeignKey("TipoDocid");

                    b.Navigation("TipoDoc");
                });
#pragma warning restore 612, 618
        }
    }
}
